# Generated by Django 4.0.5 on 2022-06-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=40)),
                ('price', models.FloatField(max_length=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('datePurchased', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('enjoyedItem', models.BooleanField(default=False)),
            ],
        ),
    ]
