# Generated by Django 4.0.5 on 2022-06-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormTest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='datePurchased',
            new_name='dateAdded',
        ),
    ]
