# Generated by Django 4.0.5 on 2022-06-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormTest', '0003_rename_item_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
