# Generated by Django 4.0.5 on 2022-06-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormTest', '0004_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
