# Generated by Django 4.0.5 on 2022-06-11 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormTest', '0005_alter_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='purchased',
        ),
    ]
